# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='Old Title', max_length=70),
        ),
    ]
